#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Apr 28 18:18:56 CEST 2025
maven-metadata-0.xml.error=
maven-metadata-0.xml.lastUpdated=1745856901474
maven-metadata-1.xml.lastUpdated=1745856901474
maven-metadata-2.xml.error=Could not transfer metadata xyz.xenondevs.commons\:commons-reflection\:1.0-SNAPSHOT/maven-metadata.xml from/to 2 (https\://repo.xenondevs.xyz/nms/)\: status code\: 401, reason phrase\: Unauthorized (401)
maven-metadata-2.xml/@default-2-https\://repo.xenondevs.xyz/nms/.lastUpdated=1745857136410
maven-metadata-3.xml.error=
maven-metadata-3.xml.lastUpdated=1745856901474
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1745856901473
